### PR TITLE
example for single pose lightning model use

### PR DESCRIPTION
**Pull request by stephanschulz**
As mentioned here I noticed that the current movenet example does not work well when a person is close to the camera.
So, I made this example using the single pose lighting model.

https://github.com/zkmkarlsruhe/ofxTensorFlow2/pull/11#issuecomment-1020602085

I don't do PRs very often and hope it did not make any mistakes.

### CODE REVIEW

**Comment by danomatika** [comment]
Is the model included? If not, that is fine as we host them separately since they would make the repo much larger. Can you provide a link the model?

**Comment by stephanschulz** [comment]
I got the model from here: https://tfhub.dev/google/movenet/singlepose/lightning/4
and downloaded [TF2.0 Saved Model (v4)](https://tfhub.dev/google/movenet/singlepose/lightning/4)
I see now that there are other options/tabs too like `A TF Lite format of google/movenet/singlepose/lightning/3` but I did not try those.

**Comment by danomatika** [comment]
Ok, thanks. Our feeling is that we don't intend to gather *all* available models into examples within this repo. This example is basically similar to the existing movenet example, so it might make more sense to house it elsewhere.

At the same time, I think it is definitely useful to add info to the existing movement example readme of how you adapted the current example to run a variant of the original model, ie. looked at model inputs/outputs and adjusted the code for it to work.

**Comment by stephanschulz** [comment]
sounds good. 
thanks for all your work on this.

**Comment by danomatika** [comment]
Closing for now.

**Pull request closed without merging**
